// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "SwiftTestHarness",
    dependencies: [
        .package(name: "AndroidSystemProperties", path: "../build/SPMPackage/macosArm64/Debug")
    ],
    targets: [
        .testTarget(
            name: "SwiftTestHarnessTests",
            dependencies: [
                .product(name: "AndroidSystemPropertiesLibrary", package: "AndroidSystemProperties")
            ],
            linkerSettings: [
                // The SPM package generated by Kotlin's embedSwiftExportForXcode
                // task contains Swift wrapper sources and C bridge declarations,
                // but the actual symbol implementations
                // (`__root____getExceptionMessage__...`) live in
                // `libAndroidSystemProperties.a` produced by the
                // `linkSwiftExportBinaryDebugStaticMacosArm64` /
                // `mergeMacosDebugSwiftExportLibraries` chain. Xcode wires
                // that archive into its own link step via
                // BUILT_PRODUCTS_DIR; a standalone `swift test` invocation
                // has to point at it explicitly. The archive lands at
                // `<repo>/build/swift-test/libAndroidSystemProperties.a` when the
                // embed task runs with the macOS Xcode-style environment
                // variables (see .github/workflows/swift.yml).
                .unsafeFlags([
                    "-L", "../build/swift-test",
                    "-lAndroidSystemProperties",
                    // `libAndroidSystemProperties.a` embeds
                    // `liborg.jetbrains.kotlin.native.platform.Foundation-cache.a` and
                    // `liborg.jetbrains.kotlin.native.platform.CoreFoundation-cache.a`,
                    // both of which reference Apple framework symbols
                    // (NSCalendarIdentifier*, NSURLUbiquitous*,
                    // CFAttributedStringGetStatisticalWritingDirections, etc.).
                    // Xcode resolves those via its own framework search, but a
                    // standalone `swift test` invocation needs the system
                    // frameworks linked explicitly.
                    "-framework", "Foundation",
                    "-framework", "CoreFoundation",
                ]),
            ]
        ),
    ]
)
